name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: install dep
        run: npm i

      # - name: run unit tests
      #   run: npm run unit

      - name: run build dev
        run: npm run build:dev

      - name: run build prod
        run: npm run build:prod
